[versions]
# libs
velocity-api = "3.4.0-SNAPSHOT"
# plugins
shadow = "9.2.0"
blossom = "1.2.0"
spotless = "8.0.0"
litecommands = "3.10.6"

[libraries]
velocitypowered-velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }
litecommands-core = { module = "dev.rollczi:litecommands-core", version.ref = "litecommands" }
litecommands-velocity = { module = "dev.rollczi:litecommands-velocity", version.ref = "litecommands" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
